### PR TITLE
set var['value'] for labels

### PR DESCRIPTION
**Pull request by zoomequipd**
hopefully ti's ok to just submit this simple pull request without an issue for it. 

reference maldoc - a294dbf604a3f508358e64bd67078d1d

### CODE REVIEW

**Comment by decalage2** [comment]
Thanks, it looks like one of the oleform tests fails on python 2.7 (not 3.x).

**Comment by zoomequipd** [comment]
Ok, I updated the tests to account for the new output, should pass ok, but...

am I correct in assuming that that based on [this comment](https://github.com/decalage2/oletools/blob/91186cdef677acd097e8b646f74dad5b0b31f31e/tests/oleform/test_basic.py#L20-L22) python2 vs python3 functionality will be different?

**Comment by decalage2** [comment]
Hi @zoomequipd, indeed currently olevba3 is not up-to-date compared to olevba for the handling of forms. I am working on merging both in the same code, but it's not done yet.

**Comment by zoomequipd** [comment]
Ok, thank you for confirming my understanding.  

I noticed #319 is still pending.  @kirk-sayre-work puts the label content into 'caption' and some other work.  I'm thinking his PR should supersede this one.  

Do you have any objections to closing this one and attempting to get #319 moved along?

**Pull request closed without merging**
