### PR TITLE
test-cases: add support for encrypted corpus

### LINKED ISSUE #215: How to deal with test data that might trigger antivirus engines
Following the question initially done in #201, I'd like to discuss it further.

After checking my sample RTF against VirusTotal, although harmless, it does trigger around 8 engines (due to heuristic checks). I've tried to change it a bit but the result was the same. I also believe that we will eventually face similar situations since we will need to simulate real malware in order to create better unit tests.

I've come up with three possible solutions (after talking to people from Intra2net):
- Encrypt or base64-encode the test data and decrypt/decode when running each test. Some utils.py file in the test folder would help here.
- Move the code to a secondary repository which contains only the unit tests and reference it as a submodule so Travis can clone it when checking PRs and commits.
- Each test creates its own test data before running, but this might get complicated and hard to maintain when dealing with complex cases.

Any other suggestion?

### PR DESCRIPTION
**Pull request by samiraguiar**
To avoid triggering antivirus engines, we can encrypt
files with a default password and decrypt them before
testing.

Closes #215

### CODE REVIEW

**Comment by samiraguiar** [comment]
@christian-intra2net encrypting files ends up breaking your unit test for json output. Do you have any suggestions on how to proceed?
I cannot pass the zip password to olevba since xglob would try to unzip all of the files, and not just the ones that are actually zipped. Also, there doesn't seem to be a way to exclude files from the iteration.

**Comment by christian-intra2net** [comment]
Just stumbled over this, must have missed a notification I got referenced here.

I guess the json unit test fails because it iterates over all files in tests/test-data and checks if running olevba[3]/msodde -j creates valid json, right. What does it produce for the encrypted zip? Did my last pull request solve this? Otherwise, what is the error?

**Comment by decalage2** [comment]
Here's the error I see in the Travis CI logs:
```
======================================================================
ERROR: test_rough_doctype (tests.ooxml.test_basic.TestOOXML)
Checks all samples, expect either ole files or good ooxml output
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/decalage2/oletools/tests/ooxml/test_basic.py", line 62, in test_rough_doctype
    acceptable = ext2doc[extn]
KeyError: 'zip'
```

**Comment by christian-intra2net** [comment]
I see, then there is an easy fix which is adding "zip" to except_extns in tests.ooxml.test_basic.TestOOXML.test_rough_doctype . It will then ignore that file.

Extending every test, that loops over all test data, to deal with encrypted zip files is probably not worth the effort, except if we plan on having lots more of zip-encrypted examples. In that case every "test-data walk()ing" test would have to be adapted (only a few at the moment).

**Comment by samiraguiar** [comment]
Thanks for the hint @christian-intra2net, it's fixed now.

**Pull request merged**
