### PR TITLE
Update plugin to latest version

### PR DESCRIPTION
**Pull request by rsaccani**
The current version has severe performance issues when analyzing some binary xls files. Updating to the latest plugin version solves the problem.

### CODE REVIEW

**Comment by decalage2** [comment]
@rsaccani could you please share some xls samples that cause performance issues?
Thanks!

**Comment by rsaccani** [comment]
Here is a test sample.
[sample.zip](https://github.com/decalage2/oletools/files/4225562/sample.zip)

**Comment by decalage2** [comment]
I tested the change after some necessary adaptations (https://github.com/decalage2/oletools/commit/783cf98cc4ed00981558c7152467bdc5f391df7f), but when I try it on your sample, it still gets stuck somewhere in plugin_biff. There is a bug that needs to be fixed. :-/

**Comment by pupaxxo** [comment]
A new version of plugin_biff was released with some "performance improvements". Applying them on the plugin file (with your patches) seems to fix it.

https://github.com/DidierStevens/DidierStevensSuite/commit/eb205ed747426c64e9abb99791db03c496863461#diff-2146c00278af18fcceb3041a386f3be1

**Comment by decalage2** [comment]
@pupaxxo I know, Didier made the fix after I told him about this issue. ;-)
I'm working on integrating it.

**Pull request merged**
