### PR TITLE
Use log helper

### PR DESCRIPTION
**Pull request by christian-intra2net**
This is a much improved version over PR #447 

Starting point is the "TODO: use log_helper" in crypto.py. This lead to using log_helper also in olevba which in turn meant making log_helper and olevba's own json-output compatible.

During work on this I realized that some logging output goes to stdout, some to stderr. Fixed that by making stdout the default for all log output.

As decalage noticed: `enable_logging` functions are required to allow logging output when importing oletools modules from other packages. Added/Updated these for olevba, crypto and record_base. Added a unittest to ensure this works.

### CODE REVIEW

**Comment by christian-intra2net** [comment]
I hope it is alright to log to stdout, I am uncertain what the result of our discussions on this topic was. Stdout is just easier because on stderr we would also have to worry about warnings (issued using `warnings.warn()` which would have to be captured and transformed in json mode

**Comment by christian-intra2net** [comment]
Rebased onto current master

**Comment by christian-intra2net** [comment]
Required a rebase after merging #365

**Comment by christian-intra2net** [comment]
Rebased to keep up-to-date

**Review by decalage2 — APPROVED** [review]

**Comment by christian-intra2net** [comment]
Thanks :)

**Pull request merged**
