### PR TITLE
Run unittests automatically on github

### PR DESCRIPTION
**Pull request by christian-intra2net**
People start relying on oletools, so we should provide a minimal amount of stability and reliability.

With this PR I propose to run the unittests for every commit to master and every pull request to master. The unittests will be started as github actions, they will run on various python versions on Windows, Mac and Linux, using CPython and PyPy.

Since we use msoffcrypt-tools, which uses cryptography, which produces warnings for python2, I could only get the unittests working by merging another branch of mine (extending the log-helper to capture warnings). Also, quite a few unittests needed fixing so they can run on windows.

### CODE REVIEW

**Comment by christian-intra2net** [comment]
For testing I have merged this branch into my fork's master, results are all green:
https://github.com/christian-intra2net/oletools/actions/runs/3548623956

**Comment by christian-intra2net** [comment]
Py 3.5 is not available any more. Since we need reliable testing, just keep the test for latest py2, py3 and pypy3.9 . Also fix tests on py2 and skip some for PyPy. Add `pylint -E`

**Comment by christian-intra2net** [comment]
Github has removed the py2-runners, so do not request them any more. There are options to replace this with docker-images, but would need to find out how to adapt solutions mentioned in https://github.com/actions/setup-python/issues/672 to our case.

**Review by decalage2 — APPROVED** [review]
Thanks a lot for all this work, sorry it took so long to merge!

**Pull request merged**
