### PR TITLE
msodde UnicodeEncodeError Fix #267

### LINKED ISSUE #267: msodde UnicodeEncodeError
Hello, I'm encountering an UnicodeEncodeError when running the latest version of msodde.

```
Traceback (most recent call last):
  File "/usr/local/bin/msodde", line 9, in <module>
    load_entry_point('oletools==0.52.2', 'console_scripts', 'msodde')()
  File "/usr/local/lib/python2.7/dist-packages/oletools/msodde.py", line 1018, in main
    text = process_file(args.filepath, args.field_filter_mode)
  File "/usr/local/lib/python2.7/dist-packages/oletools/msodde.py", line 976, in process_file
    return process_docx(filepath, field_filter_mode)
  File "/usr/local/lib/python2.7/dist-packages/oletools/msodde.py", line 611, in process_docx
    if not field_is_blacklisted(field.strip())]
  File "/usr/local/lib/python2.7/dist-packages/oletools/msodde.py", line 662, in field_is_blacklisted
    .format(contents, FIELD_BLACKLIST[index]))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 14: ordinal not in range(128)
```

A document that can reproduce this bug can be found here -> https://drive.google.com/open?id=11VHx4T4Pw9stgWxvk5k2HdgWJx4cavCG

password: oletools

### PR DESCRIPTION
**Pull request by Maijin**

### CODE REVIEW

**Comment by christian-intra2net** [comment]
You are assuming that the caller (shell) is set to encode utf8. While this is true for many modern systems, it might lead to further problems for others. A non-utf8 environment also changes the encoding of `sys.stdin` and `sys.stdout` and of encoding assumed when reading text files.
I think you should at least query `sys.getdefaultencoding` first.

See also my pull request #365 which also addresses the unicode problem

**Comment by Maijin** [comment]
Ok noted, @christian-intra2net does your PR fix 267?

**Comment by christian-intra2net** [comment]
I rebased my PR to current master and ran it on the document linked to by securitykitten. Same error appears. I will investigate

**Comment by christian-intra2net** [comment]
Upon closer investigation, this PR and the one I mentioned are related but do not solve the same problem. Mine (#365) only ensures that unicode is fine with `sys.stdout` and with `open()`. However, the problem here is that `contents` is unicode and in python2 `str.format(unicode)` will not work.

I still suggest a different fix: the logging package can deal with unicode, so what I think you should do is use unicode in all logging calls that involve contents read from the file, e.g.
```
logger.debug(u'trying to match "{0}" to blacklist command {1}'
                     .format(contents, FIELD_BLACKLIST[index]))
````
The other change (`direntry.entry_type.encode('utf-8')`) introduces an error since `direntry.entry_type` is numeric .

I will gladly create an alternative pull request if you wish

**Comment by Maijin** [comment]
Yep @christian-intra2net I'll close this one then

**Comment by christian-intra2net** [comment]
Create PR #469

**Pull request closed without merging**
